### ISSUE TITLE
Interesting Library

### ISSUE THREAD

**Issue by dealproc** [cschwarz/SignalR.Client.Portable#2]
Been searching for such a beast.  I apologize that this is a question more than an issue, but am unsure of how to contact you to ask.

How does this library fallback to other tech, like serverSentEvents, longPolling, etc. if webSockets were to fail (e.g. if you launched your server to azure, and didn't activate webSockets on the server side)?

**Comment by cschwarz** [comment]
It has been developed for websocket use only.

If you can live with serverSentEvents, Microsoft.AspNet.SignalR.Client should work in a portable environment.
